---
- name: Check SELinux status
  ansible.builtin.command: getenforce
  register: selinux_status
  changed_when: false
  ignore_errors: true

- name: Disable SELinux
  ansible.builtin.command: setenforce 0
  when: selinux_status.stdout == "Enforcing"
  notify: Reboot the system

- name: Set SELinux to be disabled on reboot
  ansible.builtin.lineinfile:
    path: /etc/selinux/config
    regexp: '^SELINUX='
    line: 'SELINUX=disabled'
  when: selinux_status.stdout == "Enforcing"
